### ISSUE TITLE
Error : String index out of range

### ISSUE THREAD

**Issue by Spl3en** [tkmru/nao#27]
Hello,

I tried running this plugin on a CTF binary from GreHack 2015 ([This one](https://grehack.fr/data/grehack2015/re/Grehack%202015%20-%20Reverse%20-%20150.zip)) and the plugin crashes when I try to run dead code elimination.

Here is the python traceback : 

    Traceback (most recent call last):
      File "D:/Logiciels/IDA6.8/scripts/nao/nao.py", line 201, in create_view
        view.Create()
      File "D:/Logiciels/IDA6.8/scripts/nao/nao.py", line 104, in Create
        self.load(ea)
      File "D:/Logiciels/IDA6.8/scripts/nao/nao.py", line 118, in load
        if not self.eliminate_deadcode(ea):
      File "D:/Logiciels/IDA6.8/scripts/nao/nao.py", line 149, in eliminate_deadcode
        if b'\x90' != i[1][0]:  # check dead code
    IndexError: string index out of range

**Comment by tkmru** [comment]
Thanks. I will try this later.

**Comment by tkmru** [comment]
@Spl3en I fixed it, Thanks for bug report.
